server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      auto-index-creation: true

server:
  port: 8080

