server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:${PWD}/config-repo
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo

