server.port: 7001
server.error.include-message: always


logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      auto-index-creation: true
      host: mongodb

server:
  port: 8080

