fullnameOverride: zipkin-server

image:
  repository: registry.hub.docker.com/openzipkin
  name: zipkin
  tag: 2.23.8
  pullPolicy: IfNotPresent

env:
  STORAGE_TYPE: mem
  ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

ports:
  - containerPort: 9411

livenessProbe_enabled: true
livenessProbe:
  httpGet:
    scheme: HTTP
    path: /actuator/info
    port: 9411
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 20
  successThreshold: 1

readinessProbe_enabled: true
readinessProbe:
  httpGet:
    scheme: HTTP
    path: /actuator/health
    port: 9411
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

