spring:
  authorization-server:
    issuer: dev-dey0yfw2zf2xbs77.us.auth0.com/

server.port: 9999
server.forward-headers-strategy: framework

spring.application.name: auth-server

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: docker

server.port: 80

---
spring.config.activate.on-profile: prod

logging.level.root: WARN